<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/pa-cockpit-video.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 23.8%; width: 12.5%; height: 1.7%;"><span class="imagemapname">PA and Cockpit Door Video</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/adirs.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 25.5%; width: 12.6%; height: 4.5%;"><span class="imagemapname">ADIRS Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/flight-control-computer.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 31.2%; width: 12.6%; height: 1.7%;"><span class="imagemapname">Flight Control Panel Left</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/evacuation.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 32.9%; width: 12.6%; height: 1.6%;"><span class="imagemapname">Evacuation Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/emergency-electric.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 34.5%; width: 12.6%; height: 1.7%;"><span class="imagemapname">Emergency Electric Power Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/gpws.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 36.2%; width: 12.6%; height: 1.5%;"><span class="imagemapname">Ground Proximity Warning Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/voice-recorder.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 37.7%; width: 12.6%; height: 1.3%;"><span class="imagemapname">Voice Recorder Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/oxygen.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 39%; width: 12.6%; height: 1.5%;"><span class="imagemapname">Oxygen Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/calls.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 40.5%; width: 12.6%; height: 1.45%;"><span class="imagemapname">Calls Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/wipers.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 41.95%; width: 12.6%; height: 2.2%;"><span class="imagemapname">Wiper Panel Capt.</span></div>
