<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/fire.jpg"><div class="imagemap" style="position: absolute; left: 35.1%; top: 25.7%; width: 30%; height: 2.7%;"><span class="imagemapname">Fire Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/hyd.jpg"><div class="imagemap" style="position: absolute; left: 35.1%; top: 28.4%; width: 30%; height: 2.3%;"><span class="imagemapname">Hydraulic Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/fuel.jpg"><div class="imagemap" style="position: absolute; left: 35.1%; top: 30.7%; width: 30%; height: 2.2%;"><span class="imagemapname">Fuel Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/elec.jpg"><div class="imagemap" style="position: absolute; left: 35.1%; top: 32.9%; width: 30%; height: 3.6%;"><span class="imagemapname">Electricity Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/ac.jpg"><div class="imagemap" style="position: absolute; left: 35.1%; top: 36.5%; width: 30%; height: 3.9%;"><span class="imagemapname">Air Condition Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/anti-ice.jpg"><div class="imagemap" style="position: absolute; left: 35.1%; top: 40.4%; width: 17.2%; height: 1.7%;"><span class="imagemapname">Anti Ice Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/cab-press.jpg"><div class="imagemap" style="position: absolute; left: 52.3%; top: 40.4%; width: 12.8%; height: 1.7%;"><span class="imagemapname">Cabin Pressure Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/ext-lt.jpg"><div class="imagemap" style="position: absolute; left: 35.1%; top: 42.1%; width: 13.3%; height: 3.2%;"><span class="imagemapname">External Lights Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/apu.jpg"><div class="imagemap" style="position: absolute; left: 48.4%; top: 42.1%; width: 3.2%; height: 3.2%;"><span class="imagemapname">APU Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/int-lt.jpg"><div class="imagemap" style="position: absolute; left: 51.6%; top: 42.1%; width: 13.5%; height: 1.4%;"><span class="imagemapname">Internal Lighting Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd/signs.jpg"><div class="imagemap" style="position: absolute; left: 51.6%; top: 43.5%; width: 13.5%; height: 1.6%;"><span class="imagemapname">Sign Panel</span></div>
