
  

<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/elt.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 2.55%; width: 12.5%; height: 1.7%;"><span class="imagemapname">ELT Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/cockpit-door.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 4.25%; width: 12.5%; height: 2.1%;"><span class="imagemapname">Cockpit Door Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/reading-light.jpg"><div class="imagemap" style="position: absolute; left: 22.5%; top: 9.9%; width: 12.5%; height: 3.3%;"><span class="imagemapname">Jump Seat Right Light</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/circuit.jpg"><div class="imagemap" style="position: absolute; left: 35%; top: 0%; width: 30.3%; height: 18%;"><span class="imagemapname">Circuit Breaker Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/pedestal-light.jpg"><div class="imagemap" style="position: absolute; left: 35%; top: 18%; width: 30.3%; height: 4.7%;"><span class="imagemapname">Pedestal Light</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/maintenance.jpg"><div class="imagemap" style="position: absolute; left: 65.3%; top: 0%; width: 12.5%; height: 8%;"><span class="imagemapname">Maintenance Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/reading-light.jpg"><div class="imagemap" style="position: absolute; left: 65.3%; top: 15.3%; width: 12.5%; height: 3.4%;"><span class="imagemapname">Jump Seat Left Light</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/ovhd-aft/fms-load.jpg"><div class="imagemap" style="position: absolute; left: 65.3%; top: 18.6%; width: 12.5%; height: 2.2%;"><span class="imagemapname">FMS Load Panel</span></div>
