<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/switching.jpg"><div class="imagemap" style="position: absolute; left: 41.2%; top: 62.5%; width: 17.6%; height: 3.0%;"><span class="imagemapname">Switching Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/ecam-control.jpg"><div class="imagemap" style="position: absolute; left: 41.2%; top: 65.5%; width: 17.6%; height: 3.3%;"><span class="imagemapname">ECAM Control Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/mcdu.jpg"><div class="imagemap" style="position: absolute; left: 28.9%; top: 62.5%; width: 12.3%; height: 9.9%;"><span class="imagemapname">MCDU Capt.</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/mcdu.jpg"><div class="imagemap" style="position: absolute; left: 58.8%; top: 62.5%; width: 12.3%; height: 9.9%;"><span class="imagemapname">MCDU F.O.</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/rmp.jpg"><div class="imagemap" style="position: absolute; left: 28.9%; top: 72.4%; width: 12.3%; height: 7.7%;"><span class="imagemapname">RMP and Audio Control Capt.</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/rmp.jpg"><div class="imagemap" style="position: absolute; left: 58.8%; top: 72.4%; width: 12.3%; height: 7.7%;"><span class="imagemapname">RMP and Audio Control F.O.</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/thrust-pitch-trim.jpg"><div class="imagemap" style="position: absolute; left: 41.2%; top: 70%; width: 17.6%; 
height: 11.7%;"><span class="imagemapname">Thrust Lever and Pitch Trim</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/engine.jpg"><div class="imagemap" style="position: absolute; left: 45.5%; top: 81.7%; width: 8.9%; height: 3.3%;"><span class="imagemapname">Engine Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/lighting-capt.jpg"><div class="imagemap" style="position: absolute; left: 28.9%; top: 80.1%; width: 12.3%; height: 2.2%;"><span class="imagemapname">Lighting Capt.</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/radar.jpg"><div class="imagemap" style="position: absolute; left: 28.9%; top: 82.3%; width: 12.3%; height: 2.8%;"><span class="imagemapname">Radar Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/lighting-aids-dfdr.jpg"><div class="imagemap" style="position: absolute; left: 58.8%; top: 80.1%; width: 12.3%; height: 2.2%;"><span class="imagemapname">Lighting, AIDS, DFDR F.O.</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/atc-tcas.jpg"><div class="imagemap" style="position: absolute; left: 58.8%; top: 82.3%; width: 12.3%; height: 2.8%;"><span class="imagemapname">ATC and TCAS Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/speedbrake.jpg"><div class="imagemap" style="position: absolute; left: 41.2%; top: 84%; width: 4.3%; height: 4.9%;"><span class="imagemapname">Speed Brake</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/flaps.jpg"><div class="imagemap" style="position: absolute; left: 54.4%; top: 84%; width: 4.3%; height: 4.9%;"><span class="imagemapname">Flaps</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/cockpit-door.jpg"><div class="imagemap" style="position: absolute; left: 34%; top: 88.9%; width: 12.3%; height: 2.6%;"><span class="imagemapname">Cockpit Door Panel</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/printer.jpg"><div class="imagemap" style="position: absolute; left: 54%; top: 88.9%; width: 12.3%; height: 7.5%;"><span class="imagemapname">Printer</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/rudder-trim.jpg"><div class="imagemap" style="position: absolute; left: 46.3%; top: 86.6%; width: 8%; height: 3.1%;"><span class="imagemapname">Rudder Trim</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/parking-brake.jpg"><div class="imagemap" style="position: absolute; left: 46.3%; top: 90.8%; width: 8%; height: 3%;"><span class="imagemapname">Parking Brake</span></div>
<img src="https://raw.githubusercontent.com/flybywiresim/docs/primary/docs/pilots-corner/assets/a32nx-briefing/pedestal/gravity-gear-ext.jpg"><div class="imagemap" style="position: absolute; left: 46.3%; top: 93.8%; width: 8%; height: 3.2%;"><span class="imagemapname">Gravity Gear Extension</span></div>